#!/bin/bash

# Script para mostrar toda la documentación del proyecto
# Autor: Sistema automatizado
# Fecha: 30 de junio de 2025

clear

echo "🏋️‍♂️ =============================================="
echo "   SISTEMA DE GESTIÓN DE GIMNASIO - AWS"
echo "        DOCUMENTACIÓN COMPLETA"
echo "=============================================="
echo ""

echo "📁 ESTRUCTURA DEL PROYECTO:"
echo "├── 📄 README.md                    ⭐ Documentación principal"
echo "├── 📄 PORTFOLIO.md                 🎯 Portfolio profesional"
echo "├── 📄 DEPLOYMENT_SUCCESS.md        ✅ Evidencia de éxito"
echo "│"
echo "├── 📁 docs/"
echo "│   ├── 📄 ARCHITECTURE.md          🏗️ Arquitectura técnica"
echo "│   ├── 📄 DEPLOYMENT_GUIDE.md      🚀 Guía de despliegue"
echo "│   ├── 📄 TERRAFORM_CODE.md        📝 Documentación de código"
echo "│   ├── 📄 monitoring-dashboard.md  📊 Guía de monitoreo"
echo "│   └── 📄 INDEX.md                 📚 Índice de documentación"
echo "│"
echo "├── 📁 scripts/"
echo "│   ├── 📄 access-dashboard.ps1     🖥️ Acceso a dashboard (Windows)"
echo "│   ├── 📄 access-dashboard.sh      🐧 Acceso a dashboard (Linux/Mac)"
echo "│   └── 📄 setup-monitoring.sh      🔧 Setup de monitoreo"
echo "│"
echo "└── 📁 terraform-modules/           🏗️ Infraestructura como código"
echo "    ├── main.tf                     Configuración principal"
echo "    ├── vpc/                        Red y conectividad"
echo "    ├── lambda/                     Funciones serverless"
echo "    ├── rds/                        Base de datos MySQL"
echo "    ├── s3/                         Almacenamiento"
echo "    ├── monitoring/                 CloudWatch dashboard"
echo "    └── iam/                        Seguridad y permisos"
echo ""

echo "🎯 PARA DIFERENTES AUDIENCIAS:"
echo ""

echo "👨‍💼 EJECUTIVOS Y MANAGERS:"
echo "   1. 📄 PORTFOLIO.md              - Resumen ejecutivo y ROI"
echo "   2. 📄 README.md                 - Visión general del proyecto"
echo "   3. 📄 DEPLOYMENT_SUCCESS.md     - Evidencia de funcionamiento"
echo ""

echo "👨‍💻 DESARROLLADORES Y DEVOPS:"
echo "   1. 📄 docs/TERRAFORM_CODE.md    - Código técnico documentado"
echo "   2. 📄 docs/ARCHITECTURE.md      - Arquitectura detallada"
echo "   3. 📄 docs/DEPLOYMENT_GUIDE.md  - Instrucciones de despliegue"
echo ""

echo "🔍 AUDITORES Y SECURITY:"
echo "   1. 📄 docs/ARCHITECTURE.md      - Seguridad y compliance"
echo "   2. 📁 iam/                      - Roles y políticas IAM"
echo "   3. 📄 docs/TERRAFORM_CODE.md    - Mejores prácticas implementadas"
echo ""

echo "📊 OPERACIONES Y SRE:"
echo "   1. 📄 docs/monitoring-dashboard.md - Guía de monitoreo"
echo "   2. 📁 scripts/                     - Herramientas de automatización"
echo "   3. 📄 docs/DEPLOYMENT_GUIDE.md     - Troubleshooting y operaciones"
echo ""

echo "🚀 ESTADO DEL PROYECTO:"
echo "   ✅ INFRASTRUCTURE: Desplegada y funcionando"
echo "   ✅ MONITORING: Dashboard activo con 9 alarmas"
echo "   ✅ DOCUMENTATION: Completa y actualizada"
echo "   ✅ TESTING: Validado y probado"
echo "   ✅ SECURITY: IAM, VPC, encryption implementados"
echo ""

echo "💰 COSTOS OPTIMIZADOS:"
echo "   💲 Lambda:      $0.20-2.00/mes (pay-per-use)"
echo "   💲 RDS:         $15.33/mes (db.t3.micro)"
echo "   💲 S3:          $0.023/GB"
echo "   💲 API Gateway: $3.50/millón requests"
echo "   💲 CloudWatch:  $3.00/mes"
echo "   💲 TOTAL:       ~$22-25/mes 💰"
echo ""

echo "🏗️ SERVICIOS AWS DESPLEGADOS:"
echo "   🌐 VPC:         vpc-01a7e41aba38531a0"
echo "   ⚡ Lambda:      3 funciones (user, booking, payment)"
echo "   🗄️ RDS:         MySQL 8.0 con db.t3.micro"
echo "   🚪 API Gateway: arn:aws:execute-api:us-east-1:xxx"
echo "   💾 S3:          gym-app-uploads"
echo "   📊 CloudWatch:  gym-infrastructure-dashboard"
echo ""

echo "🔗 LINKS IMPORTANTES:"
echo "   🖥️ Dashboard:   https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=gym-infrastructure-dashboard"
echo "   📁 GitHub:      [tu-repositorio]"
echo "   👤 LinkedIn:    [tu-perfil]"
echo ""

echo "📋 COMANDOS ÚTILES:"
echo "   # Ver outputs de Terraform"
echo "   terraform output"
echo ""
echo "   # Acceder al dashboard (Windows)"
echo "   .\\scripts\\access-dashboard.ps1"
echo ""
echo "   # Acceder al dashboard (Linux/Mac)"
echo "   ./scripts/access-dashboard.sh"
echo ""
echo "   # Probar funciones Lambda"
echo "   aws lambda invoke --function-name gym-user-management --payload '{}' response.json"
echo ""

echo "🎉 RESULTADOS DESTACADOS:"
echo "   ✅ Despliegue automatizado en 15-20 minutos"
echo "   ✅ Infraestructura escalable y serverless"
echo "   ✅ Monitoreo proactivo con alertas automáticas"
echo "   ✅ Seguridad enterprise con IAM y VPC"
echo "   ✅ Costos optimizados para startups y empresas"
echo "   ✅ Documentación completa y profesional"
echo ""

echo "📚 CÓMO USAR ESTA DOCUMENTACIÓN:"
echo ""
echo "1. 🚀 Para DESPLEGAR:"
echo "   → Lee README.md → Sigue DEPLOYMENT_GUIDE.md → Usa scripts/"
echo ""
echo "2. 📊 Para ENTENDER:"
echo "   → Revisa ARCHITECTURE.md → Consulta TERRAFORM_CODE.md"
echo ""
echo "3. 💼 Para PRESENTAR:"
echo "   → Usa PORTFOLIO.md → Muestra DEPLOYMENT_SUCCESS.md"
echo ""
echo "4. 🔧 Para OPERAR:"
echo "   → monitoring-dashboard.md → Scripts de automatización"
echo ""

echo "=============================================="
echo "   🏆 PROYECTO PRODUCTION READY 🏆"
echo "=============================================="
echo ""
echo "📞 CONTACTO:"
echo "   📧 Email:    tu-email@domain.com"
echo "   💼 LinkedIn: linkedin.com/in/tu-perfil"
echo "   🐙 GitHub:   github.com/tu-usuario"
echo ""
echo "🎯 Este proyecto demuestra competencias en:"
echo "   ✅ AWS Cloud Architecture"
echo "   ✅ Infrastructure as Code (Terraform)"
echo "   ✅ Serverless Computing"
echo "   ✅ DevOps Practices"
echo "   ✅ Monitoring & Observability"
echo "   ✅ Security Best Practices"
echo ""

echo "Presiona ENTER para continuar..."
read

echo "🎊 ¡Gracias por revisar este proyecto!"
echo "🚀 ¡Listo para llevar tu infraestructura al siguiente nivel!"
